Tax implementaion in Netsuite
fylein/fyle-netsuite-api pull request #156
Opened 2021-09-15 09:28 UTC by NileshPant1999

2021-09-15 09:49 UTC, Shwetabhk commented on apps/fyle/helpers.py
> +    fyle_platform_connection = import_string('apps.fyle.platform_connector.FylePlatformConnector')(refresh_token, workspace_id)
why are we importing it this way?

2021-09-15 09:54 UTC, Shwetabhk commented on apps/mappings/tasks.py
> +    for offset in range(0, netsuite_attributes_count, page_size):
We don't need to do batching here, a normal for loop will work
cc @ashwin1111

2021-09-15 09:55 UTC, Shwetabhk commented on apps/mappings/tasks.py
> +    for netsuite_attribute in netsuite_attributes:
How are we returning an array here? Bulk APIs do not exist currently right?

2021-09-15 09:56 UTC, Shwetabhk commented on apps/mappings/tasks.py
> +            for payload in fyle_payload:
can directly do this instead of unnecessarily creating batches, later on we'll replace it with bulk API

2021-09-15 11:45 UTC, NileshPant1999 commented on apps/mappings/tasks.py
> +    for offset in range(0, netsuite_attributes_count, page_size):
yeah we will not be getting more then 20-30 tax codes can do that without batching

2021-09-15 12:02 UTC, ashwin1111 requested changes

2021-09-15 12:02 UTC, ashwin1111 commented on apps/netsuite/connector.py
> -            'supervisorApproval': True,
why is this removed?

2021-09-15 12:02 UTC, ashwin1111 commented on apps/netsuite/connector.py
> +                "taxCode":{
single quotes to maintain consistency

2021-09-15 12:02 UTC, ashwin1111 commented on requirements.txt
> +netsuitesdk==2.3.0
platform package?

2021-09-15 12:05 UTC, NileshPant1999 commented on apps/mappings/tasks.py
> +                    'percentage': round(netsuite_attribute.detail['tax_rate']/100, 2)
no but if we don't to this it is saving like 18.000000000% which is a bit odd.

2021-09-15 12:06 UTC, NileshPant1999 commented on apps/netsuite/connector.py
> -            'supervisorApproval': True,
it was throwing a permission errror i just deleted it for testing will change this back

2021-09-16 05:40 UTC, NileshPant1999 commented on apps/fyle/platform_connector.py
> +            if response.get('data'):
it comes as []

2021-09-16 05:44 UTC, NileshPant1999 commented on apps/fyle/platform_connector.py
> +    def sync_platform_dimensions(self):
we need to add this in sync and refresh the dimensions view so that the user can refresh the dimensions after creating taxes on fyle.

2021-09-16 05:47 UTC, NileshPant1999 commented on apps/fyle/urls.py
> +    path('tax_groups/', TaxGroupsView.as_view()),
yeah we can remove added this for getting tax_groups but we are doing it in a generic way also we removed the default tax group from general mapping now so not needed.

2021-09-16 05:47 UTC, NileshPant1999 commented on apps/mappings/tasks.py
> +                'minutes': 6 * 60,
will change this

2021-09-16 05:58 UTC, NileshPant1999 commented on apps/fyle/platform_connector.py
> +    def sync_platform_dimensions(self):
yeah can remove this too

2021-09-16 06:24 UTC, NileshPant1999 commented on apps/mappings/tasks.py
> +                    'percentage': round(netsuite_attribute.detail['tax_rate']/100, 2)
no, if we are not rounding it is saving as 18.0000000000% or sometime even more zeroes.

2021-09-27 05:19 UTC, ashwin1111 requested changes

2021-09-27 05:19 UTC, ashwin1111 commented on apps/fyle/urls.py
> +    ExpenseGroupCountView, TaxGroupsView
Where is `TaxGroupsView` coming from?

2021-09-27 05:19 UTC, ashwin1111 commented on apps/mappings/tasks.py
> +    if fyle_payload:
https://github.com/fylein/fyle-netsuite-api/pull/156#discussion_r709110480

2021-09-27 05:19 UTC, ashwin1111 commented on apps/fyle/platform_connector.py
> +            if response.get('data'):
this check is not needed

2021-09-27 05:19 UTC, ashwin1111 commented on apps/fyle/views.py
> +from .platform_connector import FylePlatformConnector
Why is `FylePlatformConnector` needed here?

2021-09-27 05:19 UTC, ashwin1111 commented on apps/mappings/urls.py
> +    path('post_country/', PostCountryView.as_view()),
will check and suggest something here

2021-09-27 05:23 UTC, ashwin1111 approved these changes

2021-09-27 05:36 UTC, Sravanksk commented on apps/fyle/urls.py
> +    path('fyle_fields/', FyleFieldsView.as_view(), name='fyle-fields'),
rm extra `,`

2021-09-27 05:40 UTC, Sravanksk commented on apps/mappings/tasks.py
> +            func='apps.mappings.tasks.auto_create_tax_groups_mappings',
the function name is `auto_create_tax_group_mappings` 
but here you are triggering `apps.mappings.tasks.auto_create_tax_groups_mappings`
fix function name

2021-09-27 05:42 UTC, Shwetabhk commented on apps/mappings/tasks.py
> +                    'percentage': round(netsuite_attribute.detail['tax_rate']/100, 2)
This is fine

2021-09-27 05:48 UTC, Sravanksk approved these changes

2021-09-27 05:50 UTC, NileshPant1999 commented on apps/mappings/tasks.py
> +            func='apps.mappings.tasks.auto_create_tax_groups_mappings',
ohh missed that fixing this 👍🏻

2021-09-27 11:31 UTC, merged