Phase-1: Migrate Netsuite to platform ( Expenses API )
fylein/fyle-netsuite-api pull request #204
Opened 2022-01-10 05:43 UTC by NileshPant1999

2022-01-12 05:20 UTC, NileshPant1999 commented on apps/fyle/platform_connector.py
> -import json
can remove this entire file once all the tax-related changes in other SDKs are released.

2022-01-19 13:33 UTC, ashwin1111 commented on apps/fyle/helpers.py
> +from fyle_integrations_platform_connector import PlatformConnector
not a blocker comment, just a guideline

2022-01-19 13:33 UTC, ashwin1111 commented on apps/fyle/models.py
> -                        'amount': round(expense['amount'], 2),
why is the existing behaviour changed?

2022-01-19 13:33 UTC, ashwin1111 commented on apps/fyle/tasks.py
> +SOURCE_ACCOUNT_MAP = {
I see `SOURCE_ACCOUNT_MAP` is imported, why declare again

2022-01-19 13:33 UTC, ashwin1111 commented on requirements.txt
> -requests==2.25.0
why is this removed?

2022-01-19 13:33 UTC, ashwin1111 commented on tests/conftest.py
> +            cluster_domain='http://staging.fyle.tech/'
https

2022-01-19 13:33 UTC, ashwin1111 commented on tests/test_fyle/fixtures.py
>              "trip_request_id": None,
we don't get all these fields now

2022-01-19 13:33 UTC, ashwin1111 commented on tests/test_fyle/fixtures.py
>              "trip_request_id": None,
I assume it doesn't affect any flow, still add a todo and cleanup later if it takes time

2022-01-19 13:33 UTC, ashwin1111 commented on tests/test_fyle/fixtures.py
> +            "claim_number": "C/2021/11/R/5 - ",
is this for failing a test intentionally?

2022-01-19 13:33 UTC, ashwin1111 commented on tests/test_fyle/test_helpers.py
> +def test_check_interval_and_sync_dimension(test_connection, add_fyle_credentials):
add a todo, if this will be utilised later

2022-01-19 13:33 UTC, ashwin1111 commented on tests/test_fyle/test_platform_connector.py
> +from fyle_integrations_platform_connector import PlatformConnector
imports order

2022-01-19 14:13 UTC, NileshPant1999 commented on tests/test_fyle/fixtures.py
>              "trip_request_id": None,
yes @ashwin1111 it is a temporary fix will fix them later

2022-01-20 08:22 UTC, ashwin1111 commented on apps/fyle/models.py
> +            expense_created_at = _format_date(expense['expense_created_at'])
still this is not in alignment with the old behaviour

2022-01-20 10:26 UTC, NileshPant1999 commented on apps/fyle/models.py
> +            expense_created_at = _format_date(expense['expense_created_at'])
@ashwin1111 i didn't get what you are trying to say here

2022-01-20 10:27 UTC, NileshPant1999 commented on apps/fyle/tasks.py
> -            task_log.detail = None
why we are saving it as None it is anyway going to be even without saving it right ??

2022-01-20 11:09 UTC, ashwin1111 commented on apps/fyle/models.py
> +            expense_created_at = _format_date(expense['expense_created_at'])
These both are different right?
```
            expense_settled_at = _format_date(expense['settled_at'])
              if expense_settled_at > cutoff_date:
            
            expense_created_at = _format_date(expense['expense_created_at'])
              if expense_created_at > cutoff_date:

2022-01-20 11:11 UTC, ashwin1111 commented on apps/fyle/tasks.py
> -            task_log.detail = None
Assume a call failed to fyle api, we store the exception response in the detail column.
Now, when the next run comes, assume it went through successfully. Now, we have those faulty values in detail column even though they went through successfully.

2022-01-20 11:25 UTC, NileshPant1999 commented on apps/fyle/tasks.py
> -            task_log.detail = None
ohh okay got it thanks 🙇🏻

2022-01-20 11:32 UTC, NileshPant1999 commented on apps/fyle/models.py
> +            expense_created_at = _format_date(expense['expense_created_at'])
``` currently not getting  settled_at via the platform connector```

2022-01-27 05:53 UTC, NileshPant1999 commented on tests/test_fyle/fixtures.py
>              "trip_request_id": None,
already fixed in next pr

2022-01-27 06:02 UTC, ashwin1111 approved these changes

2022-01-27 06:04 UTC, ashwin1111 requested changes

2022-01-27 06:04 UTC, ashwin1111 commented on apps/fyle/tasks.py
> +                source_account_type, expense_group_settings.expense_state, last_synced_at, False
this has to be fixed, last param

2022-01-27 06:06 UTC, NileshPant1999 commented on apps/fyle/tasks.py
> +                source_account_type, expense_group_settings.expense_state, last_synced_at, False
okay

2022-01-27 06:19 UTC, ashwin1111 approved these changes

2022-01-27 06:25 UTC, merged