Payments Synchronization Fyle to NetSuite
fylein/fyle-netsuite-api pull request #24
Opened 2020-11-23 05:31 UTC by Sravanksk

2020-11-24 11:11 UTC, Shwetabhk commented on apps/fyle/urls.py
> +    path('reimbursements/', ReimbursementView.as_view()),
Why do we need an endpoint for this?

2020-11-24 11:12 UTC, Shwetabhk commented on apps/fyle/views.py
> +class ReimbursementView(generics.ListCreateAPIView):
Why do we need this view?

2020-11-24 11:21 UTC, Shwetabhk commented on apps/netsuite/models.py
> +    id = models.AutoField(primary_key=True)
This is wrong, the vendor payment line item does not have a foreign key reference to Vendor Payment
How are we going to identify the line items referenced to one payment

2020-11-24 11:23 UTC, Shwetabhk commented on apps/netsuite/models.py
> +        vendor_payment_lineitem_objects.append(vendor_payment_lineitem_object)
Not getting why we need this append statement if we're creating just one object
This is incorrect

2020-11-24 11:24 UTC, Shwetabhk commented on apps/netsuite/models.py
> +        vendor_payment_lineitem_objects = []
Why do we need this list if it is only going to have 1 object?

2020-11-24 11:28 UTC, Shwetabhk commented on apps/netsuite/models.py
> +    def create_vendor_payment(
Is it necessary to pass all of this info as separate arguments?
I think we only need to get expense_group_id, rest of the things can be figured out from there

2020-11-24 11:30 UTC, Shwetabhk commented on apps/netsuite/tasks.py
> +def create_vendor_payment(workspace_id):
This function is huge and unreadable, please break it down into smaller functions

2020-11-24 11:32 UTC, Shwetabhk commented on apps/netsuite/tasks.py
> +            if bills:
Everything inside this `if` block should be moved to another function
we're basically doing the same thing in all the `if` conditions, please reuse all the code, this function can be reduced to 1/3rd of it's whole size

2020-11-24 11:33 UTC, Shwetabhk commented on apps/netsuite/tasks.py
> +                            vendor_payment_object = VendorPayment.create_vendor_payment(
just pass the bill object instead of passing each and every argument

2020-11-24 11:35 UTC, Shwetabhk commented on apps/netsuite/models.py
> +    def create_vendor_payment(
just pass the `bill / expense report / journal` object here
We shouldn't unnecessarily have so many function arguments

2020-11-24 11:58 UTC, Shwetabhk commented on apps/netsuite/tasks.py
> +                            task_log.expense_group_id = bill.expense_group
please leave expense_grup id as empty, lets keep the relation only 1 to 1

2020-11-24 12:01 UTC, Shwetabhk commented on apps/netsuite/urls.py
> +    path('vendor_payments/', VendorPaymentView.as_view()),
Why do we need vendor payments url?

2020-11-24 12:01 UTC, Shwetabhk commented on apps/netsuite/tasks.py
> +            if journal_entries:
please refactor and merge into 1 function

2020-11-24 12:01 UTC, Shwetabhk commented on apps/netsuite/tasks.py
> +            if expense_reports:
please refactor and merge into 1 function

2020-11-24 12:02 UTC, Shwetabhk commented on apps/netsuite/utils.py
> +                "name": None,
single quotes

2020-11-24 12:03 UTC, Shwetabhk commented on apps/netsuite/utils.py
> +            "accountingBookDetailList": None,
please use single quotes everywhere

2020-11-24 12:04 UTC, Shwetabhk commented on apps/netsuite/views.py
> +class VendorPaymentView(generics.ListCreateAPIView):
I don't think this view is needed tight?

2020-11-24 12:24 UTC, Shwetabhk commented on apps/workspaces/models.py
> +    sync_payments = models.BooleanField(default=False, help_text='Auto Sync Payments from Fyle to Netsuite')
The name does not reflect that we're doing Fyle to NetSuite sync.
make it `sync_fyle_to_netsuite_payments`

2020-11-24 12:25 UTC, Shwetabhk commented on requirements.txt
> +netsuitesdk==1.10.0
I think now the latest version is 1.11.0
can update to that

2020-11-24 12:26 UTC, Shwetabhk commented on apps/workspaces/utils.py
> +            'sync_payments': general_settings_payload['sync_payments'],
change the name `sync_payments` it does not reflect that we're doing Fyle to NetSuite Payments

2020-11-25 05:05 UTC, Shwetabhk requested changes

2020-11-25 05:05 UTC, Shwetabhk commented on apps/netsuite/urls.py
> +    path('custom_segments/', CustomSegmentView.as_view()),
can remove the comma

2020-11-26 05:00 UTC, Shwetabhk commented on apps/netsuite/tasks.py
> +    task_log = None
Why are we initializing task_log here?

2020-11-26 05:09 UTC, Shwetabhk commented on apps/netsuite/tasks.py
> +            task_log, _ = TaskLog.objects.update_or_create(
task_log creation should be outside the `try block`, this way you can avoid the unnecessary `task_log = None`

2020-12-02 07:00 UTC, Shwetabhk commented on apps/netsuite/tasks.py
>              )
wrong indentation
move it to line 62 and make it `})`

2020-12-02 07:05 UTC, Shwetabhk commented on apps/netsuite/tasks.py
> +        if general_mapping:
just do `if general_mapping and general_mapping.vendor_payment_account_id:`

Avoid nested ifs, they decrease code readability

2020-12-02 07:05 UTC, Shwetabhk commented on apps/netsuite/tasks.py
> +                    'value': expense_group.description.get('employee_email'),
Why is the value employee email?
Email has no relevance to general mappings right?

2020-12-02 07:07 UTC, Shwetabhk commented on apps/netsuite/tasks.py
> +        if not reimbursement:
why would there be no reimbursement?
we're now removing payment pending right, then this case shouldn't come up at all

2020-12-02 07:07 UTC, Shwetabhk commented on apps/netsuite/tasks.py
> +        if not reimbursement:
is this for older entries?

2020-12-02 07:11 UTC, Shwetabhk commented on apps/netsuite/tasks.py
> +            entity_id = netsuite_object.vendor_id
why is it called vendor id for bill and entity id for ers and je?
even Vendors are entities no?

2020-12-02 07:15 UTC, Shwetabhk commented on apps/netsuite/tasks.py
> +                entity_id = line_item.entity_id
Will need to understand this whole file on a call, not able to connect the dots @Sravanksk

2020-12-02 07:16 UTC, Shwetabhk commented on apps/netsuite/utils.py
> +                    'attribute_type': 'VENDOR_PAYMENT_ACCOUNT',
why is `'_accountsPayable'` not there?

2020-12-02 07:20 UTC, Shwetabhk commented on apps/netsuite/views.py
> +    def post(self, request, *args, **kwargs):
This is incorrect usage, we don't need to implement `post` at all.
Just inherit `ListAPIView` instead of `ListCreateAPIView`
and remove the post function

2020-12-02 07:35 UTC, Sravanksk commented on apps/netsuite/tasks.py
> +                    'value': expense_group.description.get('employee_email'),
yes - we can just put a message there 
`'value' : 'payment account mapping'`

2020-12-02 07:39 UTC, Sravanksk commented on apps/netsuite/tasks.py
> +        if not reimbursement:
yes - this condition can be removed

2020-12-02 07:40 UTC, Sravanksk commented on apps/netsuite/tasks.py
> +            entity_id = netsuite_object.vendor_id
will change the column name in Bills Table to `entity_id` for consistency

2020-12-02 07:59 UTC, Sravanksk commented on apps/netsuite/utils.py
> +                    'attribute_type': 'VENDOR_PAYMENT_ACCOUNT',
payment cannot be created against account of type  `_accountsPayable`

2020-12-03 06:39 UTC, Shwetabhk commented on apps/netsuite/tasks.py
> +            for line_item in line_items:
This loop is not doing anything use `objects.first()`

2020-12-03 06:40 UTC, Shwetabhk commented on apps/netsuite/tasks.py
> +                entity_id = line_item.entity_id
Add a clickup for journal entry cleanup

2020-12-03 06:42 UTC, Shwetabhk commented on apps/netsuite/tasks.py
> +            if not (general_mapping.vendor_payment_account_id or general_mapping.vendor_payment_account_name):
This check is not needed, the job should only be scheduled once the payment account is selected

2020-12-03 06:46 UTC, Shwetabhk commented on apps/netsuite/tasks.py
> +            netsuite_object_task_log = TaskLog.objects.get(expense_group=netsuite_object.expense_group)
Move it outside the if condition

2020-12-03 06:48 UTC, Shwetabhk commented on apps/netsuite/tasks.py
> +            netsuite_object_task_log = TaskLog.objects.get(expense_group=netsuite_object.expense_group)
move this to if and the above one to else

2020-12-03 06:49 UTC, Shwetabhk commented on apps/netsuite/tasks.py
> +def create_netsite_object_payload(netsuite_objects, object_type, line_items=None):
create_netsuite_payment_objects

2020-12-03 06:49 UTC, Shwetabhk commented on apps/netsuite/tasks.py
> +    netsuite_object_payload = {}
netsuite_payment_objects

2020-12-03 06:50 UTC, Shwetabhk commented on apps/netsuite/tasks.py
> +                'unique_id': '{0}-{1}'.format(netsuite_object.external_id, netsuite_object.id),
just make sure the length does not exceed the allowed size

2020-12-03 06:52 UTC, Shwetabhk commented on apps/netsuite/tasks.py
> +    all_expenses_paid = check_expenses_status(line_items)
check_expenses_reimbursement_status

2020-12-03 06:54 UTC, Shwetabhk commented on apps/netsuite/tasks.py
> +                __validate_vendor_payment(expense_group=netsuite_object.expense_group)
This is not required

2020-12-04 12:20 UTC, Shwetabhk approved these changes

2020-12-07 07:56 UTC, Shwetabhk approved these changes

2020-12-07 07:57 UTC, merged